<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Maxwell.RuntimeHost</AssemblyName>
    <RootNamespace>Maxwell.RuntimeHost</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Activities" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
    <Reference Include="OpenRPA.Interfaces">
      <HintPath>..\runtime-staging\OpenRPA.Interfaces.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
